# Generated by Django 6.0.2 on 2026-03-03 03:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_resume'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchitectureSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('subtitle', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ArchitecturePrinciple',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('why_it_matters', models.TextField()),
                ('order', models.PositiveIntegerField(default=0)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='principles', to='portfolio.architecturesection')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
