# Generated by Django 6.0.2 on 2026-03-03 05:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_architecturesection_architectureprinciple'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projectarchitecture',
            old_name='description',
            new_name='subtitle',
        ),
        migrations.RemoveField(
            model_name='projectarchitecture',
            name='diagram',
        ),
        migrations.AddField(
            model_name='projectarchitecture',
            name='headline',
            field=models.CharField(default='Architecture Headline', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projectarchitecture',
            name='overview_title',
            field=models.CharField(default='Architecture Overview', max_length=200),
        ),
        migrations.CreateModel(
            name='ArchitectureLayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('order', models.PositiveIntegerField(default=0)),
                ('architecture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='layers', to='portfolio.projectarchitecture')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
