# Generated by Django 6.0.2 on 2026-03-06 03:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0009_alter_project_thumbnail'),
    ]

    operations = [
    ]
