# Generated by Django 6.0.2 on 2026-03-07 09:17

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0010_update_cloudinary_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutpage',
            name='profile_image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='projectdocument',
            name='file',
            field=cloudinary.models.CloudinaryField(max_length=255),
        ),
        migrations.AlterField(
            model_name='projectimage',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='file',
            field=cloudinary.models.CloudinaryField(max_length=255),
        ),
    ]
